we0ihwe

diff --git a/git-hooks/hooks/pre-commit b/git-hooks/hooks/pre-commit
--- a/git-hooks/hooks/pre-commit
+++ b/git-hooks/hooks/pre-commit
@@ -47,10 +47,12 @@ EOF
 	exit 1
 fi
 
-# I wrote this precommit hook
-exec rspec spec
-
-echo $?
+echo 'this is definitely being run potato'
+OUTPUT="$(exec rspec spec)"
+if [[ $OUTPUT =~ "Failure/Error" ]]; then
+	echo 'potato fail by humans'
+	exit 1
+fi
 
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
